### ISSUE TITLE
Improve search engine

### ISSUE THREAD

**Issue by olivier-salmon** [nexmo-community/voice-google-speechtotext#2]
The Search only returns values if you start by entering a number.
You can't search directly for a language.

If you enter Thai, it won't return anything. Whereas if you enter 1,11 or 113, the Thai language will be displayed.

A quick workaround - I suppose - would be to list the language first, then the ID.

![2018-02-08_2232](https://user-images.githubusercontent.com/19327538/36001926-1dc11e32-0d20-11e8-84c2-7dc8e5f2f4fa.png)

**Comment by sammachin** [comment]
seems to be a case sensitive issue, `thai` works but `Thai` doesn't

**Comment by sammachin** [comment]
@aaronbassett any idea how that works? I'm assuming its a built in feature of jquery? can we force the input to lower case as a workaround?
