### ISSUE TITLE
PLEASE HELP! Audio Data streamed too slow Google Speech API

### ISSUE THREAD

**Issue by axchanda** [nexmo-community/voice-google-speechtotext#6]
ERROR:
Error: 11 OUT_OF_RANGE: Audio data is being streamed too slow. Please stream audio data approximately at real time.
    at createStatusError (D:\nodejs\socket-nexmo\node_modules\grpc\src\client.js:64:15)
    at ClientDuplexStream._emitStatusIfDone
(D:\nodejs\socket-nexmo\node_modules\grpc\src\client.js:270:19)
    at ClientDuplexStream._receiveStatus (D:\nodejs\socket-nexmo\node_modules\grpc\src\client.js:248:8)
    at D:\nodejs\socket-nexmo\node_modules\grpc\src\client.js:804:12
  code: 11,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Array] } },
  details: **'Audio data is being streamed too slow. Please stream audio data approximately at real time.**' }

CODE:
var WebSocketServer = require('websocket').server;
var http = require('http');
var HttpDispatcher = require('httpdispatcher');
var dispatcher = new HttpDispatcher();
const fs = require('fs');

const speech = require('@google-cloud/speech');
const client = new speech.SpeechClient({
    keyFilename: XXXXXXXXXX
});

// Speech Recognition Initialization 
const encoding = 'LINEAR16';
const sampleRateHertz = 16000;
const languageCode = 'en-US';
const single_utterance = true;
const request = {
    config: {
        encoding: encoding,
        sampleRateHertz: sampleRateHertz,
        languageCode: languageCode
    },
    singleUtterance: true,
    interimResults: true // If you want interim results, set this to true
};

const recognizeStream = client
    .streamingRecognize(request)
    .on('error', console.error)
    .on('data', data => {
        db.get('posts')
            .push(data)
            .write();
     });

function handleRequest(request, response) {
    try {
        //log the request on console
        console.log(request.url);
        //Dispatch
        dispatcher.dispatch(request, response);
    } catch (err) {
        console.log(err);
    }
}

// Serve the ncco
dispatcher.onGet("/ncco", function (req, res) {
    fs.readFile('./ncco.json', function (error, data) {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(data, 'utf-8');
    });
});

//Create a Websocket server
var server = http.createServer(handleRequest);

var wsServer = new WebSocketServer({
    httpServer: server,
    autoAcceptConnections: true,

});

// Websockets Server Connection Configuration
wsServer.on('connect', (connection)=>{
    connection.on('message', (message) => {
              //Send to Google Speech API by passing into recognizeStream
        if (message.type === 'utf8') { console.log(message.utf8Data); }
        if (message.type === 'binary') { 
            recognizeStream.write(message.binaryData); 
        }
    });
    connection.on('close',(reasonCode, description) => {
        console.log((new Date()) + ' Peer ' + connection.remoteAddress + ' disconnected.');
    });
});

//Lets start our server
server.listen(5050, function () {
    //Callback triggered when server is successfully listening. Hurray!
    console.log("Server listening on: http://localhost:%s", 5050);
});

**Comment by axchanda** [comment]
@sammachin Can you please help me why am I facing this issue? In your code, you have downsampled and sent at 8kHz, earlier I think I saw it sent at 16kHz. Please help me on how to proceed!

**Comment by sammachin** [comment]
The audio from Nexmo is at 16Khz (although this is upsampled from the source telephpny which is only 8Khz) we've found that Google has better transcription if you give it an 8Khz source so there is a function at https://github.com/nexmo-community/voice-google-speechtotext/blob/master/server.js#L57:L69 which converts the 16Khz back to 8Khz to feed to Google.

However it looks as if you are specifying 16Khz in the config to google and sending it through un modified which should work (although possibly with lower accuracy) I've not seen that error before I suspect its something related to either your code running slow or extreme network latency

**Comment by axchanda** [comment]
@sammachin The same code works perfectly well when i stream a audio file (16kHz mono PCM file) to Google. It gives correct transcription. But gives this error message only with Nexmo telephonic call. Any ideas on this glitch. The code is also written in the comments. Please let me know how it can be corrected.

**Comment by gagandeepsinghsuri** [comment]
@sammachin I am facing the same issue. @axchanda Please let me know if you figured out a solution for this. 
Thanks

**Comment by axchanda** [comment]
@gagandeepsinghsuri It's all about in the machine you use. I tried from another PC with an super- upgraded RAM and it works perfectly fine. As @sammachin  mentioned the code is bound to run slowly as voice processing generally requires more computational power.

**Comment by gagandeepsinghsuri** [comment]
@axchanda Figured out the issue last night. For me, it was not the machine but rather the way I was tunneling my traffic from localhost. I was using ngrok & I was not getting each & every websocket event to my localhost. Updated this to server with only 1 GB of RAM and 1 CPU core, the code worked like a charm. Anyways, thanks.
