### ISSUE TITLE
Why downsampling instead of changing the rate?

### ISSUE THREAD

**Issue by amirkargar** [nexmo-community/voice-google-speechtotext#7]
Hello,

I wanted to know why did you downsample the signal to 8khz instead of changing the rate in the ncco `"content-type": "audio/l16;rate=8000"` ?

Thanks,

**Comment by mheap** [comment]
Hey @amirkargar,

When this demo was released, Nexmo didn't support 8khz websockets, only 16khz. It hasn't been updated yet to use the new functionality
